# Generated by Django 5.2.5 on 2025-09-21 14:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('external_url', models.URLField()),
                ('owner_name', models.CharField(max_length=255)),
                ('track_count', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Spotify Playlist',
                'verbose_name_plural': 'Spotify Playlists',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spotify Token',
                'verbose_name_plural': 'Spotify Tokens',
            },
        ),
        migrations.CreateModel(
            name='SpotifyTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(blank=True, max_length=255)),
                ('duration_ms', models.IntegerField(default=0)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('external_url', models.URLField()),
                ('track_number', models.IntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.spotifyplaylist')),
            ],
            options={
                'verbose_name': 'Spotify Track',
                'verbose_name_plural': 'Spotify Tracks',
                'ordering': ['track_number'],
                'unique_together': {('playlist', 'spotify_id')},
            },
        ),
    ]
