# Generated by Django 5.2.5 on 2025-10-03 08:22

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roshan", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spotifyplaylist",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Spotify Playlist",
                "verbose_name_plural": "Spotify Playlists",
            },
        ),
        migrations.RenameField(
            model_name="spotifyplaylist",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="spotifytoken",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="spotifyplaylist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="description",
            field=tinymce.models.HTMLField(
                help_text="Brief description of the resource with HTML support",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="resourcecategory",
            name="description",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Brief description of this resource category with HTML support",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="spotifyplaylist",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="spotifyplaylist",
            name="last_synced",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="spotifyplaylist",
            name="owner_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="spotifyplaylist",
            name="track_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="spotifytrack",
            name="album",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="spotifytrack",
            name="duration_ms",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="spotifytrack",
            name="track_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="spotifytrack",
            unique_together={("playlist", "spotify_id")},
        ),
    ]
