# Generated by Django 5.2.5 on 2025-10-03 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roshan', '0002_alter_spotifyplaylist_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image for the playlist', null=True, upload_to='playlists/covers/')),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manual Playlist',
                'verbose_name_plural': 'Manual Playlists',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(blank=True, max_length=255)),
                ('duration_ms', models.IntegerField(default=0, help_text='Duration in milliseconds')),
                ('audio_file', models.FileField(blank=True, help_text='Upload audio file (MP3, WAV, etc.)', null=True, upload_to='playlists/tracks/')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube URL for the track', null=True)),
                ('spotify_url', models.URLField(blank=True, help_text='Spotify URL for the track', null=True)),
                ('apple_music_url', models.URLField(blank=True, help_text='Apple Music URL for the track', null=True)),
                ('track_number', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_tracks', to='roshan.manualplaylist')),
            ],
            options={
                'verbose_name': 'Manual Track',
                'verbose_name_plural': 'Manual Tracks',
                'ordering': ['track_number', 'created_at'],
            },
        ),
    ]
