# Generated by Django 5.2.5 on 2025-10-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roshan', '0003_manualplaylist_manualtrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmeconfiguration',
            name='birthday',
            field=models.DateField(blank=True, help_text='Your birthday (used to calculate age automatically)', null=True),
        ),
        migrations.AddField(
            model_name='aboutmeconfiguration',
            name='email',
            field=models.EmailField(blank=True, default='contact@roshandamor.me', help_text='Contact email address', max_length=254),
        ),
        migrations.AddField(
            model_name='aboutmeconfiguration',
            name='followers_count',
            field=models.CharField(blank=True, default='12', help_text="Number of followers (display format like '12' or '1.2K')", max_length=20),
        ),
        migrations.AddField(
            model_name='aboutmeconfiguration',
            name='following_count',
            field=models.CharField(blank=True, default='19', help_text="Number of following (display format like '19' or '150')", max_length=20),
        ),
        migrations.AddField(
            model_name='aboutmeconfiguration',
            name='github_url',
            field=models.URLField(blank=True, default='https://github.com/logicbyroshan', help_text='GitHub profile URL'),
        ),
        migrations.AddField(
            model_name='aboutmeconfiguration',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://www.instagram.com/logicbyroshan', help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='aboutmeconfiguration',
            name='linkedin_url',
            field=models.URLField(blank=True, default='https://www.linkedin.com/in/logicbyroshan', help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='aboutmeconfiguration',
            name='location',
            field=models.CharField(blank=True, default='Bhopal, India', help_text='Your current location/address', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutmeconfiguration',
            name='open_to_work',
            field=models.BooleanField(default=True, help_text="Display 'Open to Work' status badge"),
        ),
        migrations.AddField(
            model_name='aboutmeconfiguration',
            name='twitter_url',
            field=models.URLField(blank=True, default='https://x.com/logicbyroshan', help_text='Twitter/X profile URL'),
        ),
        migrations.AddField(
            model_name='aboutmeconfiguration',
            name='website_url',
            field=models.URLField(blank=True, default='https://www.roshandamor.me', help_text='Personal website URL'),
        ),
        migrations.AddField(
            model_name='aboutmeconfiguration',
            name='youtube_url',
            field=models.URLField(blank=True, default='https://www.youtube.com/@logicbyroshan', help_text='YouTube channel URL'),
        ),
    ]
