# Generated by Django 5.2.5 on 2025-10-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roshan', '0004_aboutmeconfiguration_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmeconfiguration',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='aboutmeconfiguration',
            name='following_count',
        ),
    ]
