# Generated by Django 5.2.5 on 2025-10-16 17:05

import roshan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roshan', '0005_remove_aboutmeconfiguration_followers_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmeconfiguration',
            name='profile_image',
            field=models.FileField(blank=True, help_text='Profile image for About Me page (supports all image formats)', null=True, upload_to='about/', validators=[roshan.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='manualplaylist',
            name='cover_image',
            field=models.FileField(blank=True, help_text='Cover image for the playlist (supports all image formats)', null=True, upload_to='playlists/covers/', validators=[roshan.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='preview_image',
            field=models.FileField(blank=True, help_text='Preview image for PDFs or other documents (supports all image formats)', null=True, upload_to='resources/previews/', validators=[roshan.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='thumbnail',
            field=models.FileField(blank=True, help_text='Thumbnail image for the resource (supports all image formats)', null=True, upload_to='resources/thumbnails/', validators=[roshan.models.validate_image_file]),
        ),
    ]
