# Generated by Django 5.2.5 on 2025-10-16 17:05

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_reading_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.FileField(help_text='Upload blog cover image (supports JPG, PNG, WebP, SVG, etc.)', upload_to='blog_covers/', validators=[blog.models.validate_image_file]),
        ),
    ]
