# Generated by Django 5.2.5 on 2025-09-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmeconfiguration',
            name='intro_paragraph',
            field=models.TextField(default='This is my story, my journey, and what drives me.'),
        ),
        migrations.AlterField(
            model_name='aboutmeconfiguration',
            name='page_title',
            field=models.CharField(default='A Bit More <span>About Me</span>', max_length=255),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='summary',
            field=models.TextField(help_text='A brief description of the achievement.'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.TextField(help_text='A short excerpt for the blog list page.'),
        ),
        migrations.AlterField(
            model_name='codetogetherconfiguration',
            name='intro_paragraph',
            field=models.TextField(default="I'm always excited to collaborate on innovative projects. Here's a look at what I'm passionate about building."),
        ),
        migrations.AlterField(
            model_name='codetogetherconfiguration',
            name='page_title',
            field=models.CharField(default="Let's Build <span>Together</span>", max_length=255),
        ),
        migrations.AlterField(
            model_name='collaborationproposal',
            name='proposal',
            field=models.TextField(help_text='Detailed project proposal or collaboration idea'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(help_text='A short summary displayed on the project list page.'),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='description',
            field=models.TextField(blank=True, default='Download my latest resume to learn more about my experience and skills.'),
        ),
    ]
