# Generated by Django 5.2.5 on 2025-08-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='description',
            field=models.TextField(blank=True, default='Download my latest resume to learn more about my experience and skills.'),
        ),
        migrations.AddField(
            model_name='resume',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='technologies_used',
            field=models.CharField(blank=True, default='15+', max_length=10),
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='My Resume', max_length=200),
        ),
        migrations.AddField(
            model_name='resume',
            name='total_projects',
            field=models.CharField(blank=True, default='25+', max_length=10),
        ),
        migrations.AddField(
            model_name='resume',
            name='years_experience',
            field=models.CharField(blank=True, default='3+', max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email',
            field=models.EmailField(blank=True, default='contact@roshanproject.site', max_length=254),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='github_url',
            field=models.URLField(blank=True, default='https://github.com/logicbyroshan'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='linkedin_url',
            field=models.URLField(blank=True, default='https://www.linkedin.com/in/logicbyroshan'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='location',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='twitter_url',
            field=models.URLField(blank=True, default='https://x.com/logicbyroshan'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='youtube_url',
            field=models.URLField(blank=True, default='https://www.youtube.com/channel/logicbyroshan'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='downloadable_file',
            field=models.FileField(help_text='Upload your resume PDF file', upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='preview_image',
            field=models.ImageField(help_text='Upload a preview image of your resume (JPG/PNG recommended)', upload_to='resume/'),
        ),
    ]
