# Generated by Django 5.2.5 on 2025-09-12 07:16

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='summary',
            field=tinymce.models.HTMLField(help_text='A brief description of the achievement.'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=tinymce.models.HTMLField(help_text='A short excerpt for the blog list page.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='achievements',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='responsibilities',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='summary',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=tinymce.models.HTMLField(help_text='The main detailed content for the project detail page.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=tinymce.models.HTMLField(help_text='A short summary displayed on the project list page.'),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='Download my latest resume to learn more about my experience and skills.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='experience_description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_bio',
            field=tinymce.models.HTMLField(default='GREETINGS, ALL DIGITAL EXPLORERS! ...'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='now_description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='skills_description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='summary',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='skilltechnologydetail',
            name='learning_journey',
            field=tinymce.models.HTMLField(),
        ),
    ]
