# Generated by Django 5.2.5 on 2025-09-12 11:00

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_achievement_summary_alter_blog_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', tinymce.models.HTMLField(default='A Bit More <span>About Me</span>')),
                ('intro_paragraph', models.TextField(default='This is my story, my journey, and what drives me.', max_length=500)),
                ('profile_image', models.ImageField(blank=True, help_text='Profile image for About Me page', null=True, upload_to='about/')),
                ('detailed_description', tinymce.models.HTMLField(default="<ul>\n            <li><strong>Mission:</strong> To build software that is not only functional but also intuitive and impactful.</li>\n            <li><strong>Interests:</strong> Beyond coding, I'm passionate about AI ethics, open-source contribution, and exploring the intersection of technology and art.</li>\n        </ul>", help_text='Detailed description with HTML support')),
                ('action1_title', models.CharField(default='My Song Playlists', max_length=100)),
                ('action1_description', models.TextField(default='Discover the music that fuels my coding sessions and creative work.', max_length=300)),
                ('action1_button_text', models.CharField(default='Listen Now', max_length=50)),
                ('action2_title', models.CharField(default='Join My Community', max_length=100)),
                ('action2_description', models.TextField(default="Let's connect, share ideas, and build amazing things together.", max_length=300)),
                ('action2_button_text', models.CharField(default='Join Community', max_length=50)),
                ('action2_link', models.URLField(default='https://risetogethr.tech', help_text='External link for community')),
                ('action3_title', models.CharField(default='View My Resources', max_length=100)),
                ('action3_description', models.TextField(default='A curated list of tools, articles, and learning materials that I find valuable.', max_length=300)),
                ('action3_button_text', models.CharField(default='Explore Resources', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Me Configuration',
                'verbose_name_plural': 'About Me Configuration',
            },
        ),
    ]
