# Generated by Django 5.2.5 on 2025-08-31 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_resume_description_resume_last_updated_and_more'),
    ]

    operations = [
    ]
