# Generated by Django 5.2.5 on 2025-09-23 03:20

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_aboutmeconfiguration_intro_paragraph_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.AddField(
            model_name='technology',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_type': 'SKL'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.category'),
        ),
        migrations.AlterField(
            model_name='codetogetherconfiguration',
            name='interests_content',
            field=tinymce.models.HTMLField(help_text='Content describing your collaboration interests with HTML support'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='summary',
            field=models.TextField(help_text='A brief summary of your role and contributions.'),
        ),
        migrations.AlterField(
            model_name='resourcesconfiguration',
            name='intro_paragraph',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='resourcesconfiguration',
            name='resources_description',
            field=tinymce.models.HTMLField(blank=True, help_text='Additional description content for the resources section'),
        ),
    ]
