# Generated by Django 5.2.5 on 2025-09-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20250901_0505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'title']},
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('FRONTEND', 'Frontend Development'), ('BACKEND', 'Backend Development'), ('DATABASE', 'Database & Storage'), ('DEVOPS', 'DevOps & Deployment'), ('MOBILE', 'Mobile Development'), ('AI_ML', 'AI & Machine Learning'), ('DESIGN', 'Design & UI/UX'), ('TOOLS', 'Development Tools'), ('TESTING', 'Testing & QA'), ('OTHER', 'Other Skills')], default='OTHER', help_text='The category this skill belongs to', max_length=20),
        ),
    ]
