# Generated by Django 5.2.5 on 2025-09-12 11:16

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_aboutmeconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeTogetherConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', tinymce.models.HTMLField(default="Let's Build <span>Together</span>")),
                ('intro_paragraph', models.TextField(default="I'm always excited to collaborate on innovative projects. Here's a look at what I'm passionate about building.", max_length=500)),
                ('interests_content', tinymce.models.HTMLField(default='<ul>\n            <li><strong>AI-Powered Web Apps:</strong> Integrating ML models into practical, user-facing applications.</li>\n            <li><strong>Open-Source Tools:</strong> Creating libraries or utilities that can help other developers.</li>\n            <li><strong>Full-Stack Solutions:</strong> From database design to responsive frontends.</li>\n            <li><strong>API Development:</strong> Building robust and scalable RESTful APIs.</li>\n        </ul>', help_text='Content describing your collaboration interests with HTML support')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Code Together Configuration',
                'verbose_name_plural': 'Code Together Configuration',
            },
        ),
        migrations.CreateModel(
            name='CollaborationProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('github_id', models.CharField(blank=True, help_text='GitHub username (optional)', max_length=100)),
                ('linkedin_id', models.CharField(blank=True, help_text='LinkedIn profile URL or username (optional)', max_length=100)),
                ('proposal', tinymce.models.HTMLField(help_text='Detailed project proposal or collaboration idea')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', tinymce.models.HTMLField(blank=True, help_text='Internal notes for admin use')),
            ],
            options={
                'verbose_name': 'Collaboration Proposal',
                'verbose_name_plural': 'Collaboration Proposals',
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_role', models.CharField(help_text="e.g., 'Project Manager @ TechCorp'", max_length=200)),
                ('author_image', models.ImageField(blank=True, help_text="Author's profile picture (optional)", null=True, upload_to='testimonials/')),
                ('quote', models.TextField(help_text='The testimonial quote', max_length=500)),
                ('is_featured', models.BooleanField(default=True, help_text='Display this testimonial on the Code Together page')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_date'],
            },
        ),
    ]
