# Generated by Django 5.2.5 on 2025-09-23 05:57

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_skill_options_remove_skill_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'ordering': ['-submitted_date'], 'verbose_name': 'Contact Submission', 'verbose_name_plural': 'Contact Submissions'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='projectcomment',
            name='likes',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='summary',
            field=tinymce.models.HTMLField(help_text='A brief description of the achievement, can include HTML.'),
        ),
        migrations.AlterField(
            model_name='collaborationproposal',
            name='proposal',
            field=tinymce.models.HTMLField(help_text='Detailed project proposal or collaboration idea with HTML support'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=tinymce.models.HTMLField(help_text='Brief description of the resource with HTML support', max_length=300),
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Brief description of this resource category with HTML support', max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='quote',
            field=tinymce.models.HTMLField(help_text='The testimonial quote with HTML support'),
        ),
    ]
