# Generated by Django 5.2.5 on 2025-09-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_add_skill_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='achievements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='responsibilities',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(help_text='The main detailed content for the project detail page.'),
        ),
    ]
