# Generated by Django 5.2.5 on 2025-09-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_contactsubmission_options_remove_comment_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='technologies_used',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='total_projects',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='years_experience',
        ),
    ]
