# Generated by Django 5.2.5 on 2025-09-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_resume_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='summary',
            field=models.TextField(help_text='A brief description of the achievement, can include HTML.'),
        ),
    ]
