# Generated by Django 5.2.5 on 2025-09-16 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_resourcecategory_resourcesconfiguration_resource_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='about_description',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='about_title',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='experience_description',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='experience_title',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_bio',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='now_description',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='now_title',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='skills_description',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='skills_title',
        ),
    ]
