# Generated by Django 5.2.5 on 2025-09-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_faq_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='summary',
            field=models.TextField(),
        ),
    ]
