# Generated by Django 5.2.5 on 2025-09-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_commentlike_projectcommentlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author_avatar',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author_name',
        ),
    ]
