# Generated by Django 5.2.5 on 2025-09-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_skill_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecategory',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of this resource category with HTML support', max_length=200),
        ),
    ]
