# Generated by Django 5.2.5 on 2025-09-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_blog_author_avatar_remove_blog_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email',
            field=models.EmailField(blank=True, default='contact@roshandamor.me', max_length=254),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='location',
            field=models.CharField(blank=True, default='Bhopal, India', max_length=100),
        ),
    ]
