# Generated by Django 5.2.5 on 2025-09-23 20:57

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_resourcecategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=tinymce.models.HTMLField(help_text='Brief description of the resource with HTML support'),
        ),
    ]
