# Generated by Django 5.2.5 on 2025-10-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_remove_comment_post_remove_commentlike_comment_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AboutMeConfiguration",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="technologies",
        ),
        migrations.RemoveField(
            model_name="resourceview",
            name="resource",
        ),
        migrations.DeleteModel(
            name="ResourcesConfiguration",
        ),
        migrations.DeleteModel(
            name="ResourceCategory",
        ),
        migrations.DeleteModel(
            name="Resource",
        ),
        migrations.DeleteModel(
            name="ResourceView",
        ),
    ]
