# Generated by Django 5.2.5 on 2025-10-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_remove_through_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_tagline',
        ),
    ]
