# Generated by Django 5.2.5 on 2025-10-12 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_remove_siteconfiguration_hero_tagline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_greeting',
        ),
    ]
