# Generated by Django 5.2.5 on 2025-10-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_remove_siteconfiguration_hero_greeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_articles_stat',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_internships_stat',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_projects_stat',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_hackathons_count',
            field=models.CharField(default='12+', max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_leetcode_rating',
            field=models.CharField(default='1800+', max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_opensource_contributions',
            field=models.CharField(default='50+', max_length=10),
        ),
    ]
