# Generated by Django 5.2.5 on 2025-10-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_remove_siteconfiguration_hero_articles_stat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Mark as urgent for priority response'),
        ),
    ]
