# Generated by Django 5.2.5 on 2025-10-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_contactsubmission_is_urgent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='summary',
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('languages_frameworks', 'Languages & Frameworks'), ('backend_database', 'Backend & Database'), ('tools_platforms', 'Tools & Platforms'), ('soft_skills', 'Soft Skills')], default='languages_frameworks', help_text='Category for organizing skills on home page', max_length=50),
        ),
    ]
