# Generated by Django 5.2.5 on 2025-10-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_remove_skill_summary_skill_category'),
    ]

    operations = [
    ]
