# Generated by Django 5.2.5 on 2025-10-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_project_youtube_url_alter_project_cover_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeTogetherConfiguration',
        ),
        migrations.DeleteModel(
            name='CollaborationProposal',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
