# Generated by Django 5.2.5 on 2025-10-16 17:05

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_remove_code_together_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.FileField(blank=True, help_text='Optional: A scan or image of the certificate/award (supports all image formats).', null=True, upload_to='achievements/', validators=[portfolio.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='project_covers/', validators=[portfolio.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.FileField(upload_to='project_images/', validators=[portfolio.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='preview_image',
            field=models.FileField(help_text='Upload a preview image of your resume (supports all image formats)', upload_to='resume/', validators=[portfolio.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.FileField(blank=True, help_text='Technology icon (supports all image formats including SVG, WebP)', null=True, upload_to='tech_icons/', validators=[portfolio.models.validate_image_file]),
        ),
    ]
