# Generated by Django 5.2.5 on 2025-09-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for this context piece', max_length=200)),
                ('content', models.TextField(help_text='Supporting content about Roshan Damor - personal, background, approach, etc.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to include this in AI responses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'AI Context',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AIQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='query_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'AI Queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
