# Generated by Django 5.2.5 on 2025-09-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for this context piece', max_length=200)),
                ('content', models.TextField(help_text='Content to include in AI context')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to include this in AI responses')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher numbers appear first in context')),
                ('category', models.CharField(choices=[('about', 'About Me'), ('skills', 'Skills & Expertise'), ('experience', 'Work Experience'), ('projects', 'Projects'), ('services', 'Services'), ('contact', 'Contact Information'), ('general', 'General Information')], default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'AI Context',
                'ordering': ['-priority', 'category', 'title'],
            },
        ),
    ]
