# Generated by Django 5.2.5 on 2025-09-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aicontext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aicontext',
            options={'ordering': ['title'], 'verbose_name_plural': 'AI Context'},
        ),
        migrations.RemoveField(
            model_name='aicontext',
            name='category',
        ),
        migrations.RemoveField(
            model_name='aicontext',
            name='priority',
        ),
        migrations.AlterField(
            model_name='aicontext',
            name='content',
            field=models.TextField(help_text='Supporting content about Roshan Damor - personal, background, approach, etc.'),
        ),
    ]
