# Generated by Django 5.2.5 on 2025-09-16 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0006_remove_siteconfiguration_about_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('admin_notification', 'Admin Notification'), ('user_thankyou', 'User Thank You')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('html_content', models.TextField(help_text='HTML email content. Use {{variable}} for dynamic content.')),
                ('text_content', models.TextField(help_text='Plain text email content. Use {{variable}} for dynamic content.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(default='contact@roshandamor.me', help_text='Email address to receive contact form notifications', max_length=254)),
                ('admin_notification_enabled', models.BooleanField(default=True, help_text='Enable/disable admin email notifications')),
                ('thankyou_notification_enabled', models.BooleanField(default=True, help_text='Enable/disable thank you emails to users')),
                ('auto_mark_as_read', models.BooleanField(default=True, help_text='Automatically mark contact submissions as read after successful notification')),
                ('from_email', models.EmailField(default='noreply@roshandamor.me', help_text='From email address for outgoing notifications', max_length=254)),
                ('reply_to_email', models.EmailField(default='contact@roshandamor.me', help_text='Reply-to email address for user notifications', max_length=254)),
                ('admin_notification_delay', models.PositiveIntegerField(default=0, help_text='Delay before sending admin notification (seconds)')),
                ('thankyou_notification_delay', models.PositiveIntegerField(default=30, help_text='Delay before sending thank you email (seconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='ContactNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent_admin', 'Sent to Admin'), ('thankyou_sent', 'Thank You Sent'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('admin_email_sent', models.BooleanField(default=False)),
                ('admin_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('admin_email_error', models.TextField(blank=True, null=True)),
                ('thankyou_email_sent', models.BooleanField(default=False)),
                ('thankyou_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('thankyou_email_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='portfolio.contactsubmission')),
            ],
            options={
                'verbose_name': 'Contact Notification',
                'verbose_name_plural': 'Contact Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
