# Generated by Django 5.2.5 on 2025-10-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        # Add push notification tracking fields to ContactNotification
        migrations.AddField(
            model_name='contactnotification',
            name='push_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactnotification',
            name='push_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactnotification',
            name='push_notification_error',
            field=models.TextField(blank=True, null=True),
        ),
        
        # Add push notification settings to NotificationSettings
        migrations.AddField(
            model_name='notificationsettings',
            name='push_notification_enabled',
            field=models.BooleanField(
                default=False,
                help_text='Enable/disable push notifications for urgent messages'
            ),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='fcm_server_key',
            field=models.CharField(
                max_length=255,
                blank=True,
                help_text='Firebase Cloud Messaging server key for push notifications'
            ),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='fcm_device_token',
            field=models.CharField(
                max_length=255,
                blank=True,
                help_text="FCM device token for admin's smartphone"
            ),
        ),
    ]
