name: Deploy Django to cPanel via SSH

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CPANEL_KEY }}

      - name: Deploy to cPanel
        run: |
          ssh -p 7878 -o StrictHostKeyChecking=no ${{ secrets.CPANEL_USER }}@${{ secrets.CPANEL_HOST }} << 'EOF'
            echo "➡ Switching to project directory..."
            cd /home/roshanpr/roshandamor.me

            echo "➡ Activating virtualenv..."
            source /home/roshanpr/virtualenv/roshandamor.me/3.13/bin/activate

            echo "➡ Fetching latest code..."
            git fetch origin main
            git reset --hard origin/main

            echo "➡ Installing dependencies..."
            pip install -r requirements.txt

            echo "➡ Running migrations..."
            python manage.py migrate --noinput

            echo "➡ Collecting static files..."
            python manage.py collectstatic --noinput

            echo "➡ Restarting Passenger app..."
            touch tmp/restart.txt
          EOF
